name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install rsync -y

      - name: Deploy to EC2
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: /
          remote_path: /var/www/html/
          remote_host: 18.234.225.180
          remote_user: ec2-user
          remote_key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

