name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install rsync -y

      - name: Deploy to0 EC2
        run: |
          rsync -r --delete-after --quiet -e "ssh -i ${{ secrets.EC2_SSH_PRIVATE_KEY }}" \
            ./ ec2-user@18.234.225.180:/var/www/html/
